spring:
  application:
    name: aquariux-backend
  datasource:
    url: jdbc:h2:mem:aquariux
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.aquariux.technical.assessment.trade.entity
  configuration:
    map-underscore-to-camel-case: true
